"""empty message

Revision ID: 5ba94e2021a0
Revises: 
Create Date: 2018-04-18 21:24:41.704514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba94e2021a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'personalfolders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personalfolders', type_='foreignkey')
    # ### end Alembic commands ###
